"""ThemeManager — applies the QSS generated by QssBuilder to the application.

Usage::

    ThemeManager.instance().apply(app)
    ThemeManager.instance().set_font_scale(app, base_pt=15)
    ThemeManager.instance().get_color(ColorRole.ACCENT_ALT)   # → "#D8B36A"
    ThemeManager.instance().get_font_size_px(FontSize.SMALL)  # → 12 (at default scale)
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from PySide6.QtGui import QFont, QFontDatabase
from PySide6.QtWidgets import QApplication

from theme.qss_builder import QSS_BASE_PX, QssBuilder
from theme.spec import (
    DARK_NAVY,
    FONT_SIZE_BASE_PX,
    ColorRole,
    FontRole,
    FontSize,
    ThemeSpec,
)

log = logging.getLogger(__name__)

# Font files to register with Qt — resolved relative to this file so the path
# works in both dev and Nuitka builds.
_THEME_DIR       = Path(__file__).resolve().parent
_ASSETS_FONTS_DIR = _THEME_DIR.parent / "assets" / "fonts"

_FONT_FILES: list[str] = [
    "Orbitron-Variable.ttf",
]

# ── User-facing font-size options ──────────────────────────────────────────────
# These map a human-readable label to a base pt value.  All QSS font sizes scale
# proportionally relative to QSS_BASE_PX (13 px) at each of these pt values.
FONT_SIZE_OPTIONS: list[tuple[str, int]] = [
    ("Small (11 pt)",       11),
    ("Normal (14 pt)",      14),
    ("Large (16 pt)",       16),
    ("Extra Large (19 pt)", 19),
    ("Huge (23 pt)",        23),
]

_DEFAULT_FONT_PT: int = 14


class ThemeManager:
    """Centralised theme controller — singleton, access via ``ThemeManager.instance()``.

    Responsibilities
    ----------------
    * Register bundled fonts with Qt.
    * Build and apply the application stylesheet via ``QssBuilder``.
    * Expose helpers so widgets can read theme values without raw hex strings.
    * Support runtime theme and font-scale changes with a single call.
    """

    _instance: Optional["ThemeManager"] = None

    def __init__(self) -> None:
        self._spec:             ThemeSpec = DARK_NAVY
        self._current_font_pt:  int       = _DEFAULT_FONT_PT
        self._fonts_loaded:     bool      = False

    # ── Singleton ──────────────────────────────────────────────────────────────

    @classmethod
    def instance(cls) -> "ThemeManager":
        """Return the global ThemeManager, creating it if necessary."""
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    # ── Public API ─────────────────────────────────────────────────────────────

    def apply(self, app: QApplication, base_font_size_pt: int = _DEFAULT_FONT_PT) -> None:
        """Register fonts and apply the stylesheet to *app*.

        Parameters
        ----------
        app:
            The running ``QApplication`` instance.
        base_font_size_pt:
            Point size for the UI base font.  All QSS ``font-size`` values are
            scaled proportionally relative to the 13 px reference scale.
        """
        self._register_fonts()
        self._apply(app, base_font_size_pt)
        log.debug(
            "Theme applied — spec=%r  font=%d pt",
            self._spec.name,
            base_font_size_pt,
        )

    def set_font_scale(self, app: QApplication, base_font_size_pt: int) -> None:
        """Change the font scale at runtime and immediately re-apply the stylesheet.

        Call this from the Appearance page when the user changes the font size.
        QSS is regenerated from the current spec — no disk I/O.
        """
        self._apply(app, base_font_size_pt)
        log.info("Font scale changed → %d pt", base_font_size_pt)

    def set_theme(self, app: QApplication, spec: ThemeSpec) -> None:
        """Swap the active ThemeSpec and immediately re-apply the stylesheet.

        Parameters
        ----------
        app:
            The running ``QApplication`` instance.
        spec:
            The new ``ThemeSpec`` to activate.
        """
        self._spec = spec
        self._apply(app, self._current_font_pt)
        log.info("Theme changed → %r", spec.name)

    def reload(self, app: QApplication) -> None:
        """Re-apply the current spec at the current font scale (useful in dev)."""
        self._apply(app, self._current_font_pt)
        log.info("Theme reloaded")

    # ── Theme value helpers ────────────────────────────────────────────────────

    def get_color(self, role: ColorRole) -> str:
        """Return the hex/rgba colour string for *role* in the active theme."""
        return self._spec.color(role)

    def get_font(self, role: FontRole) -> str:
        """Return the font-family name string for *role* in the active theme."""
        return self._spec.font_family(role)

    def get_font_size_px(self, size: FontSize) -> int:
        """Return the current scaled px value for *size*.

        The result reflects both the authored base px (from ``FONT_SIZE_BASE_PX``)
        and the user's chosen ``current_font_pt``.
        """
        scale = self._current_font_pt / QSS_BASE_PX
        authored = FONT_SIZE_BASE_PX[size]
        return max(8, round(authored * scale))

    @property
    def current_font_pt(self) -> int:
        """Currently active base font size in points."""
        return self._current_font_pt

    @property
    def current_spec(self) -> ThemeSpec:
        """The currently active ThemeSpec."""
        return self._spec

    # ── Private helpers ────────────────────────────────────────────────────────

    def _apply(self, app: QApplication, pt: int) -> None:
        """Build QSS from the current spec + pt, then apply to *app*."""
        self._current_font_pt = pt
        qss = QssBuilder.build(self._spec, pt)
        app.setStyleSheet(qss)
        app.setFont(QFont(self._spec.font_family(FontRole.BODY), pt))

    def _register_fonts(self) -> None:
        """Register bundled fonts with Qt's font database (runs once)."""
        if self._fonts_loaded:
            return
        for filename in _FONT_FILES:
            font_path = _ASSETS_FONTS_DIR / filename
            if font_path.exists():
                fid = QFontDatabase.addApplicationFont(str(font_path))
                if fid == -1:
                    log.warning("Failed to register font: %s", filename)
                else:
                    families = QFontDatabase.applicationFontFamilies(fid)
                    log.debug("Registered font %s → %s", filename, families)
            else:
                log.info(
                    "Font not found — run scripts/download_fonts.py: %s", font_path
                )
        self._fonts_loaded = True

